### ISSUE TITLE
Can't build for iOS production

### ISSUE THREAD

**Issue by 91seguros** [Harishn28/react-native-signview#2]
Hi! I've been using react-native-signview with Android and it works perfectly.
But now when I try to compile it for iOS, i get the following error: "ld: library not found for -lReactNativeSignView". Strangely, it works fine when debuggin in XCode Simulator or an actual iPhone.

react-native: 0.57.8
react-native-signview: 1.0.5

Could you please help me fixing this?
Thank you!

**Comment by Harishn28** [comment]
Sorry @91seguros  did it worked ??
If not i'll look at it ASAP

**Comment by Harishn28** [comment]
Fixed in version 1.0.6. Please update your version to 1.0.6 in package.json.
rm package-lock.json
npm install and try building your app again.
